### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by hxwork** [fuqichen1998/Deformer#1]
Hi,

Your work is really amazing! May I know when will the code be released? Looking forward to your reply.

**Comment by karimknaebel** [comment]
+1 @fuqichen1998

**Comment by yxt7979** [comment]
+1 @fuqichen1998  Thank you so much!

**Comment by DachunKai** [comment]
+1 @fuqichen1998

**Comment by fuqichen1998** [comment]
Hi all, we took some time to cleanup, and the code is released now. Thanks for your patience!
