### ISSUE TITLE
CodaLab error

### ISSUE THREAD

**Issue by cgz6498** [fuqichen1998/Deformer#14]
<img width="359" alt="2854e1980bf883192826f26de42e69b" src="https://github.com/fuqichen1998/Deformer/assets/77420384/57136850-8283-411a-819e-d17b8d843947">

Hello, I failed to open the View scoring error log when I was verifying on the official website.

 WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap. /opt/conda/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment. warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.') You are using pip version 9.0.1, however version 24.0 is available. You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by fuqichen1998** [comment]
The issue does not belong to this repo, please post it in the right place.
