### ISSUE TITLE
results

### ISSUE THREAD

**Issue by cgz6498** [fuqichen1998/Deformer#15]
Hello. After training, the results are not good.
loss is:
 (epoch: 50, time: Tue Apr 23 06:34:08 2024),mano_mesh3d_loss:1.97979736328125,mano_joints3d_loss:2.0168581008911133,manopose_loss:0.2283429056406021,manoshape_loss:0.21703919768333435,mano_total_loss:4.442031383514404,hm_joints2d_loss:1.0113672018051147,dynamic_mano_mesh3d_loss:4.234370231628418,dynamic_mano_joints3d_loss:4.312495231628418,dynamic_mano_pose_loss:0.4501177966594696,dynamic_end2end_mesh3d_loss:1.7039984464645386,dynamic_end2end_joints3d_loss:1.7303528785705566,dynamic_end2end_manopose_loss:0.21645528078079224,dynamic_mano_total_loss:12.647767066955566,total_loss:18.1012020111084
 results is:
 Evaluation 3D KP results:
auc=0.074, mean_kp3d_avg=14.26 cm
Evaluation 3D KP PROCRUSTES ALIGNED results:
auc=0.792, mean_kp3d_avg=1.04 cm
Evaluation 3D KP SCALE-TRANSLATION ALIGNED results:
auc=0.074, mean_kp3d_avg=14.58 cm

Evaluation 3D MESH results:
auc=0.042, mean_kp3d_avg=13.78 cm
Evaluation 3D MESH ALIGNED results:
auc=0.796, mean_kp3d_avg=1.02 cm

F-scores
F@5.0mm = 0.035 	F_aligned@5.0mm = 0.469
F@15.0mm = 0.167 	F_aligned@15.0mm = 0.947
my options is:
    parser.add_argument("--data_root",default="/media/server/b881b6e5-25e5-4720-8777-d170e360ba1e/ho3dv2", type=str, help="dataset root")
    parser.add_argument("--mano_root", default=r"/home/server/Deformer-main/assets/mano_models", type=str, help="mano root")
    parser.add_argument("--obj_model_root",default="/home/server/Deformer-main/assets/object_models",type=str, help="object model root")
    parser.add_argument("--inp_res", default=512, type=int, help="input image size")
    ## additional options for the temporal dataset
    parser.add_argument("--T", default=7, type=int, help="the number of frames in a sequence")
    parser.add_argument("--gap", default=10, type=int, help="the gap between two consecutive frames")

    # options for model
    parser.add_argument("--model",default="deformer",choices=["deformer"],help="network core architecture")
    parser.add_argument("--channels",default=256,type=int,help="Number of channels in the hourglass (default: 256)")
    ## additional options for deformer
    parser.add_argument("--transformer_layer", default=3,type=int,help="Number of  transformer encoder/decoder(default:6)")
    parser.add_argument("--transformer_head",default=8,type=int,help="Number of transformer attention head")
    parser.add_argument("--transformer_dim_feedforward",default=256,type=int,help="Transformer feedforward dimension")
    parser.add_argument("--temporal_transformer_layer",default=3,type=int,help="Number of temporal transformer encoder/decoder(default:6)")
    parser.add_argument("--temporal_transformer_head",default=8,type=int,help="Number of temporal transformer attention head")
    parser.add_argument("--temporal_constrained",dest="temporal_constrained",action="store_true",help="Add temporal loss")
    #### additional options for discriminator
    parser.add_argument("--motion_discrimination",dest="motion_discrimination",action="store_true",help="Add motion discriminator")

    # options for loss
    parser.add_argument("--mano_neurons",nargs="+",default=[1024, 512],type=int,help="Number of neurons in hidden layer for mano decoder")
    parser.add_argument("--mano_lambda_joints3d",default=1e4,type=float,help="Weight to supervise joints in 3d")
    parser.add_argument("--mano_lambda_verts3d",default=1e4,type=float,help="Weight to supervise vertices in 3d")
    parser.add_argument("--mano_lambda_manopose",default=10,type=float,help="Weight to supervise mano pose parameters")
    parser.add_argument("--mano_lambda_manoshape",default=0.1, type=float,help="Weight to supervise mano shape parameters")
    parser.add_argument("--mano_lambda_regulshape",default=1e2,type=float,help="Weight to regularize hand shapes")
    parser.add_argument("--mano_lambda_regulpose",default=1,type=float,help="Weight to regularize hand pose in axis-angle space")
    parser.add_argument("--lambda_joints2d",default=1e2,type=float,help="Weight to supervise joints in 2d")
    ## temporal constrains
    parser.add_argument("--temporal_mano_lambda_joints3d",default=1e4,type=float,help="Weight to supervise joints in 3d")
    parser.add_argument("--temporal_mano_lambda_verts3d",default=1e4,type=float,help="Weight to supervise vertices in 3d")
    parser.add_argument("--temporal_mano_lambda_manopose",default=10,type=float,help="Weight to supervise mano pose parameters")
    parser.add_argument("--temporal_mano_lambda_manoshape",default=0.1,type=float,help="Weight to supervise mano shape parameters")
    ## dynamic constrains
    parser.add_argument("--dynamic_mano_lambda_joints3d",default=1e4,type=float,help="Weight to supervise joints in 3d")
    parser.add_argument("--dynamic_mano_lambda_verts3d",default=1e4,type=float,help="Weight to supervise vertices in 3d")
    parser.add_argument("--dynamic_mano_lambda_manopose",default=10,type=float,help="Weight to supervise mano pose parameters")
    parser.add_argument("--dynamic_mano_lambda_manoshape",default=0.1,type=float,help="Weight to supervise mano shape parameters")
    parser.add_argument("--end2end_mano_lambda_joints3d",default=1e4,type=float,help="Weight to supervise joints in 3d")
    parser.add_argument("--end2end_mano_lambda_verts3d",default=1e4,type=float,help="Weight to supervise vertices in 3d")
    parser.add_argument("--end2end_mano_lambda_manopose",default=10,type=float,help="Weight to supervise mano pose parameters")
    ## discrimination loss
    parser.add_argument("--motion_dis_loss_weight",default=10,type=float,help="Weight to supervise mano shape parameters")
    ## adaptive loss
    parser.add_argument("--loss_base", default="maxmse", type=str)

    # options for training
    parser.add_argument("--manual_seed", default=0, type=int, help="manual seed")
    parser.add_argument("-j","--workers",default=12,type=int,help="number of data loading workers (default: 16)")
    parser.add_argument("--epochs", default=60, type=int, help="number of total epochs to run")
    parser.add_argument("--train_batch", default=12, type=int, help="Train batch size")
    parser.add_argument("--test_batch", default=16, type=int, metavar="N", help="Test batch size")
    parser.add_argument("--lr","--learning-rate",default=1e-5,type=float,help="initial learning rate")
    parser.add_argument("--lr_backbone","--learning-rate-backbone",default=1e-4,type=float,help="initial learning rate for backbone")
    parser.add_argument("--momentum", default=0.9, type=float)
    parser.add_argument("--lr_decay_step",default=10,type=int,help="epochs after which to decay learning rate")
    parser.add_argument("--lr_decay_gamma",default=0.7,type=float,help="factor by which to decay the learning rate")
    parser.add_argument("--weight_decay", default=0.0005, type=float)
    ## additional options for discriminator
    parser.add_argument("--motion_dis_lr", default=1e-3, type=float, help="initial learning rate")
    parser.add_argument("--motion_dis_lr_decay_step", default=10, type=int, help="initial learning rate")
    parser.add_argument("--motion_dis_weight_decay",default=0.0005,type=float,help="initial learning rate" )
    parser.add_argument("--motion_dis_lr_decay_gamma",default=0.7,type=float,help="initial learning rate")

    # options for exp
    parser.add_argument("--host_folder",default="experiments/ho3d_train",type=str,help="path to save experiment results")
    parser.add_argument("--resume", type=str, default="",help="path to latest checkpoint")
    parser.add_argument("--evaluate", dest="evaluate", action="store_true", help="evaluate model")
    parser.add_argument("--save_results", default=True, help="save output results of the network")
    parser.add_argument("--test_freq", default=2,type=int,metavar="N",help="testing frequency on evaluation dataset",)
    parser.add_argument("--snapshot",default=1, type=int,metavar="N",help="How often to take a snapshot of the model (0 = never)",

**Comment by HonglinChu** [comment]
Hi, how can you get this info
"
results is:
Evaluation 3D KP results:
auc=0.074, mean_kp3d_avg=14.26 cm
Evaluation 3D KP PROCRUSTES ALIGNED results:
auc=0.792, mean_kp3d_avg=1.04 cm
Evaluation 3D KP SCALE-TRANSLATION ALIGNED results:
auc=0.074, mean_kp3d_avg=14.58 cm

Evaluation 3D MESH results:
auc=0.042, mean_kp3d_avg=13.78 cm
Evaluation 3D MESH ALIGNED results:
auc=0.796, mean_kp3d_avg=1.02 cm

F-scores
[F@5.0mm](mailto:F@5.0mm) = 0.035 [F_aligned@5.0mm](mailto:F_aligned@5.0mm) = 0.469
[F@15.0mm](mailto:F@15.0mm) = 0.167 [F_aligned@15.0mm](mailto:F_aligned@15.0mm) = 0.947
"

**Comment by HonglinChu** [comment]
(epoch: 30, time: Fri Apr 26 19:40:40 2024),mano_mesh3d_loss:20.50520896911621,mano_joints3d_loss:21.026891708374023,manopose_loss:0.618351936340332,manoshape_loss:0.521459698677063,mano_total_loss:42.672122955322266,hm_joints2d_loss:5.785449028015137,dynamic_mano_mesh3d_loss:47.50978469848633,dynamic_mano_joints3d_loss:48.58854293823242,dynamic_mano_pose_loss:1.281796932220459,dynamic_end2end_mesh3d_loss:18.113388061523438,dynamic_end2end_joints3d_loss:18.555177688598633,dynamic_end2end_manopose_loss:0.5709832310676575,dynamic_mano_total_loss:134.61929321289062,total_loss:193.076904296875,model_motion_disc_loss:9.99992847442627,motion_disc_loss_real:2.083778781525325e-05,motion_disc_loss_fake:2.3662145395064726e-05,motion_disc_loss:4.449986954568885e-05
(epoch: 31, time: Sat Apr 27 05:09:01 2024),mano_mesh3d_loss:18.575210571289062,mano_joints3d_loss:19.063507080078125,manopose_loss:0.5965661406517029,manoshape_loss:0.5041494369506836,mano_total_loss:38.73942184448242,hm_joints2d_loss:5.711339473724365,dynamic_mano_mesh3d_loss:43.95746612548828,dynamic_mano_joints3d_loss:44.97278594970703,dynamic_mano_pose_loss:1.2376022338867188,dynamic_end2end_mesh3d_loss:16.822105407714844,dynamic_end2end_joints3d_loss:17.236373901367188,dynamic_end2end_manopose_loss:0.555219829082489,dynamic_mano_total_loss:124.78146362304688,total_loss:179.23223876953125,model_motion_disc_loss:9.999972343444824,motion_disc_loss_real:7.605116934428224e-06,motion_disc_loss_fake:6.259764631977305e-06,motion_disc_loss:1.3864908396499231e-05
(epoch: 32, time: Sat Apr 27 14:07:06 2024),mano_mesh3d_loss:17.563566207885742,mano_joints3d_loss:18.03289794921875,manopose_loss:0.5782120227813721,manoshape_loss:0.4917002320289612,mano_total_loss:36.666419982910156,hm_joints2d_loss:5.656409740447998,dynamic_mano_mesh3d_loss:42.13494873046875,dynamic_mano_joints3d_loss:43.11299133300781,dynamic_mano_pose_loss:1.204711675643921,dynamic_end2end_mesh3d_loss:16.05354881286621,dynamic_end2end_joints3d_loss:16.447877883911133,dynamic_end2end_manopose_loss:0.5426276326179504,dynamic_mano_total_loss:119.49674987792969,total_loss:171.8194580078125,model_motion_disc_loss:10.000266075134277,motion_disc_loss_real:7.359681148955133e-06,motion_disc_loss_fake:6.153479716886068e-06,motion_disc_loss:1.3513130397768691e-05
(epoch: 33, time: Sat Apr 27 23:05:43 2024),mano_mesh3d_loss:17.865564346313477,mano_joints3d_loss:18.32662582397461,manopose_loss:0.5744565725326538,manoshape_loss:0.4851609170436859,mano_total_loss:37.251808166503906,hm_joints2d_loss:5.611181735992432,dynamic_mano_mesh3d_loss:42.73039245605469,dynamic_mano_joints3d_loss:43.69643020629883,dynamic_mano_pose_loss:1.200778603553772,dynamic_end2end_mesh3d_loss:16.14162826538086,dynamic_end2end_joints3d_loss:16.530040740966797,dynamic_end2end_manopose_loss:0.538667619228363,dynamic_mano_total_loss:120.837646484375,total_loss:173.7004852294922,model_motion_disc_loss:9.99991226196289,motion_disc_loss_real:2.2255433577811345e-05,motion_disc_loss_fake:2.1417177777038887e-05,motion_disc_loss:4.367255314718932e-05
(epoch: 34, time: Sun Apr 28 08:04:14 2024),mano_mesh3d_loss:17.560792922973633,mano_joints3d_loss:18.01565933227539,manopose_loss:0.5676557421684265,manoshape_loss:0.4809828996658325,mano_total_loss:36.625118255615234,hm_joints2d_loss:5.61295747756958,dynamic_mano_mesh3d_loss:42.15971374511719,dynamic_mano_joints3d_loss:43.11039352416992,dynamic_mano_pose_loss:1.1856895685195923,dynamic_end2end_mesh3d_loss:15.93644905090332,dynamic_end2end_joints3d_loss:16.318225860595703,dynamic_end2end_manopose_loss:0.5323245525360107,dynamic_mano_total_loss:119.24295043945312,total_loss:171.48117065429688,model_motion_disc_loss:9.999947547912598,motion_disc_loss_real:7.178326086432207e-06,motion_disc_loss_fake:6.006411240377929e-06,motion_disc_loss:1.3184700037527364e-05

My train loss seems more bad than you!

**Comment by cgz6498** [comment]
I obtained the training loss according to the method provided by the author, and then submitted the result to codalab to get the above result. Do you have the problems with #14 ?

**Comment by cgz6498** [comment]
@HonglinChu 
I obtained the training loss according to the method provided by the author, and then submitted the result to codalab to get the above result. Do you have any problems with #14 ?

**Comment by fuqichen1998** [comment]
Can you share the loss curves of the training to see if they converge?

**Comment by cgz6498** [comment]
@fuqichen1998 
I don't know how to draw the loss curve, so I've provided a partial loss value for training. It can be seen that the loss is decreasing, but the loss decreases very little in the later stage of training.

==== log  at Fri Apr 19 09:44:30 2024 ====
(epoch: 1, time: Fri Apr 19 11:22:58 2024),mano_mesh3d_loss:47.81787872314453,mano_joints3d_loss:48.650672912597656,manopose_loss:3.0040230751037598,manoshape_loss:1.0513725280761719,mano_total_loss:100.52379608154297,hm_joints2d_loss:4.250576972961426,dynamic_mano_mesh3d_loss:97.71672058105469,dynamic_mano_joints3d_loss:99.45774841308594,dynamic_mano_pose_loss:5.69537878036499,dynamic_end2end_mesh3d_loss:46.840721130371094,dynamic_end2end_joints3d_loss:47.67106628417969,dynamic_end2end_manopose_loss:2.733949661254883,dynamic_mano_total_loss:300.11505126953125,total_loss:404.890380859375
(epoch: 5, time: Fri Apr 19 18:24:05 2024),mano_mesh3d_loss:10.737244606018066,mano_joints3d_loss:10.788188934326172,manopose_loss:0.690610408782959,manoshape_loss:0.5262277722358704,mano_total_loss:22.742267608642578,hm_joints2d_loss:3.027156352996826,dynamic_mano_mesh3d_loss:24.412582397460938,dynamic_mano_joints3d_loss:24.58506202697754,dynamic_mano_pose_loss:1.3591201305389404,dynamic_end2end_mesh3d_loss:10.740550994873047,dynamic_end2end_joints3d_loss:10.810196876525879,dynamic_end2end_manopose_loss:0.6604929566383362,dynamic_mano_total_loss:72.56803894042969,total_loss:98.33750915527344
(epoch: 10, time: Sat Apr 20 02:58:50 2024),mano_mesh3d_loss:6.174041271209717,mano_joints3d_loss:6.3391432762146,manopose_loss:0.3619577884674072,manoshape_loss:0.42189931869506836,mano_total_loss:13.29702091217041,hm_joints2d_loss:2.2531728744506836,dynamic_mano_mesh3d_loss:13.693918228149414,dynamic_mano_joints3d_loss:14.029352188110352,dynamic_mano_pose_loss:0.7155700922012329,dynamic_end2end_mesh3d_loss:5.857436656951904,dynamic_end2end_joints3d_loss:6.013731956481934,dynamic_end2end_manopose_loss:0.3484627306461334,dynamic_mano_total_loss:40.65842056274414,total_loss:56.20857238769531
(epoch: 15, time: Sat Apr 20 11:41:15 2024),mano_mesh3d_loss:4.294012069702148,mano_joints3d_loss:4.405137538909912,manopose_loss:0.3200874626636505,manoshape_loss:0.36590149998664856,mano_total_loss:9.385159492492676,hm_joints2d_loss:1.8521831035614014,dynamic_mano_mesh3d_loss:9.30610466003418,dynamic_mano_joints3d_loss:9.532752990722656,dynamic_mano_pose_loss:0.6322434544563293,dynamic_end2end_mesh3d_loss:3.942452907562256,dynamic_end2end_joints3d_loss:4.041807174682617,dynamic_end2end_manopose_loss:0.30805152654647827,dynamic_mano_total_loss:27.763458251953125,total_loss:39.000728607177734
(epoch: 20, time: Sat Apr 20 20:18:10 2024),mano_mesh3d_loss:3.5353176593780518,mano_joints3d_loss:3.6209781169891357,manopose_loss:0.292706161737442,manoshape_loss:0.31820982694625854,mano_total_loss:7.767207145690918,hm_joints2d_loss:1.5857220888137817,dynamic_mano_mesh3d_loss:7.597069263458252,dynamic_mano_joints3d_loss:7.77230167388916,dynamic_mano_pose_loss:0.5781906843185425,dynamic_end2end_mesh3d_loss:3.2281975746154785,dynamic_end2end_joints3d_loss:3.3024380207061768,dynamic_end2end_manopose_loss:0.2812284529209137,dynamic_mano_total_loss:22.759384155273438,total_loss:32.11240768432617
(epoch: 25, time: Sun Apr 21 05:01:28 2024),mano_mesh3d_loss:2.9462890625,mano_joints3d_loss:3.0138099193573,manopose_loss:0.2748122215270996,manoshape_loss:0.2866578698158264,mano_total_loss:6.5215606689453125,hm_joints2d_loss:1.4040035009384155,dynamic_mano_mesh3d_loss:6.324944972991943,dynamic_mano_joints3d_loss:6.462615489959717,dynamic_mano_pose_loss:0.5424824953079224,dynamic_end2end_mesh3d_loss:2.6383016109466553,dynamic_end2end_joints3d_loss:2.692546844482422,dynamic_end2end_manopose_loss:0.263197660446167,dynamic_mano_total_loss:18.92414665222168,total_loss:26.849681854248047
(epoch: 30, time: Sun Apr 21 13:37:02 2024),mano_mesh3d_loss:2.6597769260406494,mano_joints3d_loss:2.7177278995513916,manopose_loss:0.2611794173717499,manoshape_loss:0.2645179331302643,mano_total_loss:5.903218746185303,hm_joints2d_loss:1.277262806892395,dynamic_mano_mesh3d_loss:5.694150924682617,dynamic_mano_joints3d_loss:5.8131561279296875,dynamic_mano_pose_loss:0.515462338924408,dynamic_end2end_mesh3d_loss:2.3724679946899414,dynamic_end2end_joints3d_loss:2.41890549659729,dynamic_end2end_manopose_loss:0.24961626529693604,dynamic_mano_total_loss:17.063739776611328,total_loss:24.244190216064453
(epoch: 35, time: Sun Apr 21 22:24:46 2024),mano_mesh3d_loss:2.392857074737549,mano_joints3d_loss:2.4424076080322266,manopose_loss:0.25069716572761536,manoshape_loss:0.24714963138103485,mano_total_loss:5.333106994628906,hm_joints2d_loss:1.1835317611694336,dynamic_mano_mesh3d_loss:5.122355937957764,dynamic_mano_joints3d_loss:5.224593639373779,dynamic_mano_pose_loss:0.49447453022003174,dynamic_end2end_mesh3d_loss:2.1073508262634277,dynamic_end2end_joints3d_loss:2.1446518898010254,dynamic_end2end_manopose_loss:0.2389553338289261,dynamic_mano_total_loss:15.332378387451172,total_loss:21.849014282226562
(epoch: 40, time: Mon Apr 22 06:59:02 2024),mano_mesh3d_loss:2.2497880458831787,mano_joints3d_loss:2.2942142486572266,manopose_loss:0.24183496832847595,manoshape_loss:0.2343374490737915,mano_total_loss:5.020180702209473,hm_joints2d_loss:1.1137497425079346,dynamic_mano_mesh3d_loss:4.804470062255859,dynamic_mano_joints3d_loss:4.8965654373168945,dynamic_mano_pose_loss:0.47674235701560974,dynamic_end2end_mesh3d_loss:1.9779458045959473,dynamic_end2end_joints3d_loss:2.0109992027282715,dynamic_end2end_manopose_loss:0.2299271672964096,dynamic_mano_total_loss:14.396685600280762,total_loss:20.530582427978516
(epoch: 45, time: Mon Apr 22 21:57:48 2024),mano_mesh3d_loss:2.078843593597412,mano_joints3d_loss:2.118579149246216,manopose_loss:0.23453080654144287,manoshape_loss:0.22447650134563446,mano_total_loss:4.65642786026001,hm_joints2d_loss:1.0568970441818237,dynamic_mano_mesh3d_loss:4.444976329803467,dynamic_mano_joints3d_loss:4.528267860412598,dynamic_mano_pose_loss:0.46218764781951904,dynamic_end2end_mesh3d_loss:1.8010010719299316,dynamic_end2end_joints3d_loss:1.8295384645462036,dynamic_end2end_manopose_loss:0.2225557565689087,dynamic_mano_total_loss:13.288522720336914,total_loss:19.001846313476562
(epoch: 50, time: Tue Apr 23 06:34:08 2024),mano_mesh3d_loss:1.97979736328125,mano_joints3d_loss:2.0168581008911133,manopose_loss:0.2283429056406021,manoshape_loss:0.21703919768333435,mano_total_loss:4.442031383514404,hm_joints2d_loss:1.0113672018051147,dynamic_mano_mesh3d_loss:4.234370231628418,dynamic_mano_joints3d_loss:4.312495231628418,dynamic_mano_pose_loss:0.4501177966594696,dynamic_end2end_mesh3d_loss:1.7039984464645386,dynamic_end2end_joints3d_loss:1.7303528785705566,dynamic_end2end_manopose_loss:0.21645528078079224,dynamic_mano_total_loss:12.647767066955566,total_loss:18.1012020111084
(epoch: 55, time: Tue Apr 23 15:22:33 2024),mano_mesh3d_loss:1.8726028203964233,mano_joints3d_loss:1.9068670272827148,manopose_loss:0.2231632024049759,manoshape_loss:0.2099669873714447,mano_total_loss:4.212603569030762,hm_joints2d_loss:0.9793380498886108,dynamic_mano_mesh3d_loss:4.011414051055908,dynamic_mano_joints3d_loss:4.084848880767822,dynamic_mano_pose_loss:0.44001269340515137,dynamic_end2end_mesh3d_loss:1.595276117324829,dynamic_end2end_joints3d_loss:1.619146704673767,dynamic_end2end_manopose_loss:0.21130946278572083,dynamic_mano_total_loss:11.961997985839844,total_loss:17.15392303466797
(epoch: 60, time: Wed Apr 24 00:33:11 2024),mano_mesh3d_loss:1.792427659034729,mano_joints3d_loss:1.8241523504257202,manopose_loss:0.21834638714790344,manoshape_loss:0.20432372391223907,mano_total_loss:4.039251804351807,hm_joints2d_loss:0.9474028944969177,dynamic_mano_mesh3d_loss:3.8434784412384033,dynamic_mano_joints3d_loss:3.9122984409332275,dynamic_mano_pose_loss:0.4306645095348358,dynamic_end2end_mesh3d_loss:1.5042744874954224,dynamic_end2end_joints3d_loss:1.525123953819275,dynamic_end2end_manopose_loss:0.20654277503490448,dynamic_mano_total_loss:11.42238998413086,total_loss:16.409029006958008
(epoch: 65, time: Wed Apr 24 09:35:32 2024),mano_mesh3d_loss:1.726232647895813,mano_joints3d_loss:1.755853295326233,manopose_loss:0.21470777690410614,manoshape_loss:0.199045330286026,mano_total_loss:3.8958423137664795,hm_joints2d_loss:0.9264094829559326,dynamic_mano_mesh3d_loss:3.6978518962860107,dynamic_mano_joints3d_loss:3.7624566555023193,dynamic_mano_pose_loss:0.4235624372959137,dynamic_end2end_mesh3d_loss:1.439171314239502,dynamic_end2end_joints3d_loss:1.4584144353866577,dynamic_end2end_manopose_loss:0.20287546515464783,dynamic_mano_total_loss:10.98433780670166,total_loss:15.806622505187988

**Comment by fuqichen1998** [comment]
The results show your training is not converged. Note 5% loss drop per epoch is not "little". Please double-check check the hyperparameters (batch_size, epochs, etc.) are the same as described, and make sure the training is converged.

**Comment by cgz6498** [comment]
@fuqichen1998 
Is there no problem with the above option? If not, I'll train again from the beginning and try.
In addition, is question #14  the problem of Codalab? Did you make this error when you submitted the results?

**Comment by fuqichen1998** [comment]
I hadn't encountered that error before.

**Comment by cgz6498** [comment]
Hello, I retrained the model, but the training loss is still very high. Here are the training results. Could you please check if there are any issues with my hyperparameters?
(epoch: 1, time: Sat May  4 09:26:10 2024),mano_mesh3d_loss:45.83012390136719,mano_joints3d_loss:46.65694046020508,manopose_loss:2.418076753616333,manoshape_loss:1.077453851699829,mano_total_loss:95.98279571533203,hm_joints2d_loss:4.241191387176514,dynamic_mano_mesh3d_loss:94.04896545410156,dynamic_mano_joints3d_loss:95.79463195800781,dynamic_mano_pose_loss:4.916504859924316,dynamic_end2end_mesh3d_loss:45.12123107910156,dynamic_end2end_joints3d_loss:45.98126220703125,dynamic_end2end_manopose_loss:2.4519405364990234,dynamic_mano_total_loss:288.3137512207031,total_loss:398.5360107421875,model_motion_disc_loss:9.9981107711792,motion_disc_loss_real:0.000733902445062995,motion_disc_loss_fake:0.00044269513455219567,motion_disc_loss:0.001176602323539555
(epoch: 5, time: Sat May  4 17:38:18 2024),mano_mesh3d_loss:9.952059745788574,mano_joints3d_loss:10.201780319213867,manopose_loss:0.4509437382221222,manoshape_loss:0.4342362880706787,mano_total_loss:21.039085388183594,hm_joints2d_loss:2.855187177658081,dynamic_mano_mesh3d_loss:22.27250099182129,dynamic_mano_joints3d_loss:22.80674171447754,dynamic_mano_pose_loss:0.8068405389785767,dynamic_end2end_mesh3d_loss:9.776982307434082,dynamic_end2end_joints3d_loss:10.025270462036133,dynamic_end2end_manopose_loss:0.39334461092948914,dynamic_mano_total_loss:66.08171081542969,total_loss:99.90675354003906,model_motion_disc_loss:9.93068790435791,motion_disc_loss_real:0.004267061594873667,motion_disc_loss_fake:0.003531991969794035,motion_disc_loss:0.007799049839377403
(epoch: 10, time: Sun May  5 03:51:49 2024),mano_mesh3d_loss:5.6661763191223145,mano_joints3d_loss:5.812982082366943,manopose_loss:0.35668250918388367,manoshape_loss:0.3775058686733246,mano_total_loss:12.21330451965332,hm_joints2d_loss:2.0360264778137207,dynamic_mano_mesh3d_loss:12.231619834899902,dynamic_mano_joints3d_loss:12.54102897644043,dynamic_mano_pose_loss:0.6551112532615662,dynamic_end2end_mesh3d_loss:5.305083274841309,dynamic_end2end_joints3d_loss:5.4488067626953125,dynamic_end2end_manopose_loss:0.3198094069957733,dynamic_mano_total_loss:36.501461029052734,total_loss:60.72380447387695,model_motion_disc_loss:9.972930908203125,motion_disc_loss_real:0.0018929144134745002,motion_disc_loss_fake:0.0015642086509615183,motion_disc_loss:0.0034571171272546053
(epoch: 15, time: Sun May  5 14:14:03 2024),mano_mesh3d_loss:3.922316312789917,mano_joints3d_loss:4.020729064941406,manopose_loss:0.3085628151893616,manoshape_loss:0.3260708153247833,mano_total_loss:8.577653884887695,hm_joints2d_loss:1.6485226154327393,dynamic_mano_mesh3d_loss:8.37734317779541,dynamic_mano_joints3d_loss:8.581984519958496,dynamic_mano_pose_loss:0.5836836099624634,dynamic_end2end_mesh3d_loss:3.5796964168548584,dynamic_end2end_joints3d_loss:3.6677989959716797,dynamic_end2end_manopose_loss:0.28583040833473206,dynamic_mano_total_loss:25.07634925842285,total_loss:45.28411865234375,model_motion_disc_loss:9.981524467468262,motion_disc_loss_real:0.001063354080542922,motion_disc_loss_fake:0.0010520289652049541,motion_disc_loss:0.002115382347255945
(epoch: 20, time: Mon May  6 00:28:05 2024),mano_mesh3d_loss:3.243656873703003,mano_joints3d_loss:3.3225181102752686,manopose_loss:0.2856326103210449,manoshape_loss:0.28766727447509766,mano_total_loss:7.1394805908203125,hm_joints2d_loss:1.395870327949524,dynamic_mano_mesh3d_loss:6.865237712860107,dynamic_mano_joints3d_loss:7.024870872497559,dynamic_mano_pose_loss:0.5344903469085693,dynamic_end2end_mesh3d_loss:2.9227030277252197,dynamic_end2end_joints3d_loss:2.988758087158203,dynamic_end2end_manopose_loss:0.2609747350215912,dynamic_mano_total_loss:20.59705924987793,total_loss:39.10090255737305,model_motion_disc_loss:9.968480110168457,motion_disc_loss_real:0.0013991995947435498,motion_disc_loss_fake:0.001621764968149364,motion_disc_loss:0.0030209599062800407
(epoch: 21, time: Mon May  6 02:36:06 2024),mano_mesh3d_loss:2.9852712154388428,mano_joints3d_loss:3.055757761001587,manopose_loss:0.278152734041214,manoshape_loss:0.2790164053440094,mano_total_loss:6.59818696975708,hm_joints2d_loss:1.3490018844604492,dynamic_mano_mesh3d_loss:6.323657989501953,dynamic_mano_joints3d_loss:6.465837478637695,dynamic_mano_pose_loss:0.5235587954521179,dynamic_end2end_mesh3d_loss:2.659008264541626,dynamic_end2end_joints3d_loss:2.7162914276123047,dynamic_end2end_manopose_loss:0.2558702528476715,dynamic_mano_total_loss:18.94420623779297,total_loss:36.87388229370117,model_motion_disc_loss:9.98238468170166,motion_disc_loss_real:0.000811489881016314,motion_disc_loss_fake:0.0010479969205334783,motion_disc_loss:0.0018594862194731832
(epoch: 22, time: Mon May  6 04:34:40 2024),mano_mesh3d_loss:2.892200231552124,mano_joints3d_loss:2.9602885246276855,manopose_loss:0.2734980285167694,manoshape_loss:0.2741641700267792,mano_total_loss:6.400139331817627,hm_joints2d_loss:1.3147553205490112,dynamic_mano_mesh3d_loss:6.131006240844727,dynamic_mano_joints3d_loss:6.268869400024414,dynamic_mano_pose_loss:0.5162487626075745,dynamic_end2end_mesh3d_loss:2.5760726928710938,dynamic_end2end_joints3d_loss:2.6318061351776123,dynamic_end2end_manopose_loss:0.2523154318332672,dynamic_mano_total_loss:18.376317977905273,total_loss:36.079742431640625,model_motion_disc_loss:9.988606452941895,motion_disc_loss_real:0.0005509900511242449,motion_disc_loss_fake:0.0006957058794796467,motion_disc_loss:0.001246696338057518
(epoch: 23, time: Mon May  6 06:43:06 2024),mano_mesh3d_loss:2.8074448108673096,mano_joints3d_loss:2.871513843536377,manopose_loss:0.2688893973827362,manoshape_loss:0.2675214409828186,mano_total_loss:6.215362548828125,hm_joints2d_loss:1.2847247123718262,dynamic_mano_mesh3d_loss:5.957469940185547,dynamic_mano_joints3d_loss:6.087929725646973,dynamic_mano_pose_loss:0.5096595883369446,dynamic_end2end_mesh3d_loss:2.4972972869873047,dynamic_end2end_joints3d_loss:2.5495078563690186,dynamic_end2end_manopose_loss:0.24903278052806854,dynamic_mano_total_loss:17.85089874267578,total_loss:35.331321716308594,model_motion_disc_loss:9.980391502380371,motion_disc_loss_real:0.000976355338934809,motion_disc_loss_fake:0.0010080300271511078,motion_disc_loss:0.0019843867048621178

**Comment by fuqichen1998** [comment]
The log shows the loss is in the normal range. The hyperparameters should be consistent with the repo's README.
