### ISSUE TITLE
Looking for guidance on generating motion dict pickle files

### ISSUE THREAD

**Issue by ElectronicElephant** [fuqichen1998/Deformer#2]
Hi,

Thanks for the awesome work. We are trying to run the training pipeline on DexYCB dataset and find the following error msg:

```
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/homes/XXXX/XXXX/dex-ycb/dexycb_s0_motion_dict.pickle'
```

I suppose it's not from the original dataset, but generated by some preprocessing process in order to accelerate training. I am wondering if you can tell me how to generate such file. Thanks!

**Comment by fuqichen1998** [comment]
Good catch! Just added the script. Please see the last commit and updated README.
