### ISSUE TITLE
miss HO3D sequence list

### ISSUE THREAD

**Issue by yxt7979** [fuqichen1998/Deformer#3]
Hii, I'm trying to reproduce this wonderful work in the HO3D dataset.

After I unzip ho3d-process.zip, I found the sequence_list file is missing, but generate_motions.py needs it: https://github.com/fuqichen1998/Deformer/blob/main/scripts/generate_motions.py#L56
Could you please share the train_temporal_windows_{T}_{gap}.json file?

![image](https://github.com/fuqichen1998/Deformer/assets/62125435/8ddabb0c-a9c8-4d02-9600-844a54257f21)

**Comment by fuqichen1998** [comment]
The `train_temporal_windows_{T}_{gap}.json` will be generated when you launch the training at the first time. Then you can run `generate_motions.py`, and launch the training again.
