### ISSUE TITLE
Looking for (yet another) guidance on generating coverage json files

### ISSUE THREAD

**Issue by ElectronicElephant** [fuqichen1998/Deformer#4]
Hi,

Nice to meet you (again, lol).

I am still working on training on YCB dataset and got this error:

```
AssertionError: File does not exists: dexycb-process/s0_train_coverage.json
```

It seems that it's generated by some preprocessing process in order to accelerate training. I would appreciate it if you could upload the scripts to generate it. Thanks.

Bests,

T.T.T.

**Comment by ElectronicElephant** [comment]
Hmm, it seems that it's not used in the training pipeline. Can I safely comment it out?

**Comment by fuqichen1998** [comment]
Yes, it is not used in the training pipeline, please feel free to comment it out or pull the latest commit.
