### ISSUE TITLE
Demo for in the wild tests

### ISSUE THREAD

**Issue by yxt7979** [fuqichen1998/Deformer#5]
Hii, sorry for bothering you again. I found that you use HO3D and Dex datasets; could you please share the demo codes for testing with a custom video? Thank you so much!

**Comment by fuqichen1998** [comment]
Unfortunately, we lost the checkpoints during a lab NAS cleaning and I don't have the bandwidth (I have graduated) and resources to re-train the models. However, we released the training code and instructions that you are welcome to train the models by yourself.
