### ISSUE TITLE
How to launch the training at the first time to generate the train_temporal_windows_{T}_{gap}.json

### ISSUE THREAD

**Issue by Chinatown123** [fuqichen1998/Deformer#7]
How to launch the training at the first time to generate the train_temporal_windows_{T}_{gap}.json? 
I try to run "python -m torch.distributed.launch --nproc_per_node 4 ddp_train.py --data_root=/data/xuanda/data/HO3D_v2/ --model "deformer" --train_batch=1 --test_batch=3 --workers 12 --T 7 --gap 10 --transformer_layer 3 --temporal_transformer_layer 3 --lr 1e-5 --motion_dis_lr 1e-3 --motion_discrimination --loss_base "maxmse" --snapshot 5 --host_folder=experiments/ho3d_train --run_name ho3d_train".
Then I still get "AssertionError: File does not exists: ho3d-process/train_temporal_windows_7_10.json".

**Comment by fuqichen1998** [comment]
Good catch, thanks for spotting the issue. We fixed it by adding the preprocess script, could you please try the latest commit (62d8b21)?
