### ISSUE TITLE
关于process_dexycb数据预处理

### ISSUE THREAD

**Issue by HonglinChu** [fuqichen1998/Deformer#8]
你好，感谢你的开源工作，我在运行 python -m scripts.generate_motions --data_root=xxx/Deformer-main/dataset/dex_ycb 的时候 报错
AssertionError: File does not exists: ./dexycb-process/train_temporal_windows_7_10.json

然后发现preprocess_dexycb.py代码里面确实没有生成temporal_windows相关的json
而preprocess_ho3d.py 是有生成temporal_windows相关的json代码的

**Comment by fuqichen1998** [comment]
你可以先跑train command， 尽管会fail，但是会自动生成temporal_windows相关的json。 在此之后可以继续跑generate_motions 和launch training。

**Comment by HonglinChu** [comment]
感谢您的及时回复，我们已经按照您的建议成功生成了对应的json文件，现在两个数据集都可以正常训练。另外还有一个问题，是否方便提供手部时序mesh和误差可视化的脚本代码以方便我们对比（尽管知道您是借鉴了VIBE和TCMR）
![image](https://github.com/fuqichen1998/Deformer/assets/11087575/e08eccab-dedc-4239-9e30-d01316c4c600)

**Comment by cgz6498** [comment]
Hello, the author has a new link for YCB, but there is no points.xyz file for each object, where should I find it?

**Comment by fuqichen1998** [comment]
@HonglinChu Here are some uncleaned code that you may use to visualize the predictions and error maps:

```
            jet_cmap = cm.get_cmap("jet")
            gt_hand_verts, gt_hand_joints = mano_layer(
                th_pose_coeffs=gt_mano_pose, th_betas=gt_mano_shape, th_trans=gt_mano_trans)
            gt_hand_verts, gt_hand_joints = gt_hand_verts[0], gt_hand_joints[0]
            gt_hand_verts[:, 1] *= -1
            gt_hand_verts[:, 2] *= -1
            
            pred_mano_shape = torch.tensor(pred_mano_shape_list[pidx])[None]
            pred_mano_pose = torch.tensor(pred_mano_pose_list[pidx])[None]
            hand_verts, hand_joints = mano_layer(
                th_pose_coeffs=pred_mano_pose, th_betas=pred_mano_shape, th_trans=gt_mano_trans)
            hand_verts, hand_joints = hand_verts[0], hand_joints[0]
            hand_verts[:, 1] *= -1
            hand_verts[:, 2] *= -1
            
            hand_verts_error = (gt_hand_verts - hand_verts).norm(dim=1)
            hand_verts_error_color = jet_cmap(hand_verts_error.cpu().numpy() / max_val)
            
            cam_intr = dexycb_dataset.K[idx].copy()
            
            scene_r = create_scene(
                hand_verts, cam_intr, mano_layer, hand_verts_color=hand_verts_error_color, black_bg=True)
            r = pyrender.OffscreenRenderer(viewport_width=w, viewport_height=h)
            im_render, _ = r.render(scene_r)
            r.delete()
            render_dict['error_bg'] = im_render
            
            scene_r = create_scene(hand_verts, cam_intr, mano_layer, wire_frame=True, black_bg=True)
            r = pyrender.OffscreenRenderer(viewport_width=w, viewport_height=h)
            im_render_wire, _ = r.render(scene_r)
            r.delete()
            render_dict['wire_bg'] = im_render_wire
```

**Comment by fuqichen1998** [comment]
@cgz6498 This work doesn't need `points.xyz` so you can comment out all code that reads/processes it. Meanwhile, please move any followup irrelevant to this issue to a separate issue.

**Comment by cgz6498** [comment]
jet_cmap = cm.get_cmap("jet")
            gt_hand_verts, gt_hand_joints = mano_layer(
                th_pose_coeffs=gt_mano_pose, th_betas=gt_mano_shape, th_trans=gt_mano_trans)
            gt_hand_verts, gt_hand_joints = gt_hand_verts[0], gt_hand_joints[0]
            gt_hand_verts[:, 1] *= -1
            gt_hand_verts[:, 2] *= -1
            
            pred_mano_shape = torch.tensor(pred_mano_shape_list[pidx])[None]
            pred_mano_pose = torch.tensor(pred_mano_pose_list[pidx])[None]
            hand_verts, hand_joints = mano_layer(
                th_pose_coeffs=pred_mano_pose, th_betas=pred_mano_shape, th_trans=gt_mano_trans)
            hand_verts, hand_joints = hand_verts[0], hand_joints[0]
            hand_verts[:, 1] *= -1
            hand_verts[:, 2] *= -1
            
            hand_verts_error = (gt_hand_verts - hand_verts).norm(dim=1)
            hand_verts_error_color = jet_cmap(hand_verts_error.cpu().numpy() / max_val)
            
            cam_intr = dexycb_dataset.K[idx].copy()
            
            scene_r = create_scene(
                hand_verts, cam_intr, mano_layer, hand_verts_color=hand_verts_error_color, black_bg=True)
            r = pyrender.OffscreenRenderer(viewport_width=w, viewport_height=h)
            im_render, _ = r.render(scene_r)
            r.delete()
            render_dict['error_bg'] = im_render
            
            scene_r = create_scene(hand_verts, cam_intr, mano_layer, wire_frame=True, black_bg=True)
            r = pyrender.OffscreenRenderer(viewport_width=w, viewport_height=h)
            im_render_wire, _ = r.render(scene_r)
            r.delete()
            render_dict['wire_bg'] = im_render_wire

**Comment by cgz6498** [comment]
Hello, you provided visualize the predictions and error maps code, how to use the above code?Qualitative Can you provide Results on the HO3D code ?

**Comment by cgz6498** [comment]
Hello, you provided visualize the predictions and error maps code, how to use the above code?Qualitative Can you provide Results on the HO3D code ?

**Comment by HonglinChu** [comment]
Thank you very much！

**Comment by HonglinChu** [comment]
Thank you very much！

**Comment by fuqichen1998** [comment]
No problem!
